# Unique key for this project in SonarQube
sonar.projectKey=cricbook

# URL of the SonarQube server
sonar.host.url=http://16.113.14.173:9000/

# Display name of the project
sonar.projectName=CricBook

# Project version
sonar.projectVersion=1.0.0

# Comma-separated paths to directories containing source code
sonar.sources=cricbook-next,services

# Exclusions to avoid analyzing node_modules, config files, charts, build artifacts, etc.
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/.swc/**,helm/**,argocd-setup/**,*.exe,ebs-trust-policy.json,**/*.yaml,**/*.yml,*.json,*.config.js,*.config.ts

# Encoding of the source code
sonar.sourceEncoding=UTF-8

#docker run --rm -v "$(pwd):/usr/src" sonarsource/sonar-scanner-cli -Dsonar.token="sqa_c2ed2917bd23c71f66ac8f4dba26cd1d046e7ab5"
