{{- if .Values.db.enabled }}
# PersistentVolumeClaim: pgdata-pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cricbook.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.db.storageClassName }}
  storageClassName: {{ .Values.db.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.db.storage }}
---
{{- end }}

# PersistentVolumeClaim: ollama-data-pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cricbook.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.ollama.storageClassName }}
  storageClassName: {{ .Values.ollama.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.ollama.storage }}
