# PersistentVolumeClaim: pgdata-pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cricbook.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.storage }}

---
# PersistentVolumeClaim: ollama-data-pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cricbook.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ollama.storage }}
